update jedi dependencies to add python 3.13 support (#24330)
Once at a time I switched to jedi language server but find it didn't
work.

I checked the error and find that the error was:
```
  File "***data\extensions\ms-python.python-2024.16.1-universal\python_files\lib\jedilsp\jedi\inference\__init__.py", line 91, in __init__
    self.grammar = environment.get_grammar()
                   ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "***data\extensions\ms-python.python-2024.16.1-universal\python_files\lib\jedilsp\jedi\cache.py", line 112, in wrapper
    result = method(self, *args, **kwargs)
  File "***data\extensions\ms-python.python-2024.16.1-universal\python_files\lib\jedilsp\jedi\api\environment.py", line 37, in get_grammar
    return parso.load_grammar(version=version_string)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "***data\extensions\ms-python.python-2024.16.1-universal\python_files\lib\jedilsp\parso\grammar.py", line 264, in load_grammar
    raise NotImplementedError(message)
NotImplementedError: Python version 3.13 is currently not supported.
```

I tracked down and find that parso 0.8.4 added python3.13 support

So the dependencies needs to be updated